version: "3.8"

services:

#mdns
  mdns:
    container_name: mdns
    image: damonmorgan/traefik-mdns
    environment:
      SERVER_HOST_NAME: 'entertainer'
      SERVER_DOMAIN_NAME: 'local'
      NETWORK_INTERFACE: 'enp2s0'
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/dbus-1/system.d:/system-dbus
    network_mode: "host"
    privileged: true
    restart: unless-stopped

#Reverse Proxy
  traefik:
    container_name: traefik
    image: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`traefik.local`, `traefik.lan`)"
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.services.admin.loadbalancer.server.port=8080"
    restart: unless-stopped

# HTPC Portal
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/heimdall:/config
    environment:
      PGID: 1000
      PUID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.local`, `heimdall.lan`)"
      - "traefik.http.routers.heimdall.entrypoints=web"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
    restart: unless-stopped

# TV
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/sonarr:/config
      - ${TV_DESTINATION_PATH}:/tv
      - ${PROCESSING_PATH}/downloads:/downloads
    environment:
      PGID: 1000
      PUID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.local`, `sonarr.lan`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    restart: unless-stopped

# Torrent Proxy
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/jackett:/config
      - ${PROCESSING_PATH}/jackett-downloads:/downloads
    environment:
      PGID: 1000
      PUID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.local`, `jackett.lan`)"
      - "traefik.http.routers.jackett.entrypoints=web"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
    restart: unless-stopped

# Torrent Downloader
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/transmission:/config
      - ${PROCESSING_PATH}/downloads:/downloads
      - ${PROCESSING_PATH}/jackett-downloads:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      PGID: 1000
      PUID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.local`, `transmission.lan`)"
      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
    restart: unless-stopped

# Tor proxy so jackett can bypass ISP filters (NOT for anonymity - use something like Tails for that)
  torproxy:
    container_name: torproxy
    image: rdsubhas/tor-privoxy-alpine
    ports:
      - "8118:8118"
      - "9050:9050"
    restart: unless-stopped

# Auto update containers
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    command: --cleanup --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

# Backups
  crashplan-pro:
    container_name: crashplan
    image: jlesage/crashplan-pro
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/crashplan:/config
      - ${BACKUP_PATH}:/storage
    environment:
      GROUP_ID: 1000
      USER_ID: 1000
      CRASHPLAN_SRV_MAX_MEM: 3072M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crashplan.rule=Host(`crashplan.local`, `crashplan.lan`)"
      - "traefik.http.routers.crashplan.entrypoints=web"
      - "traefik.http.services.crashplan.loadbalancer.server.port=5800"
    restart: unless-stopped

# Pihole
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/etc-pihole/:/etc/pihole/
      - ${CONTAINERS_CONFIG_PATH}/etc-dnsmasqd/:/etc/dnsmasq.d/
    environment:
      DNS1: 1.1.1.3
      DNS2: 1.0.0.3
      VIRTUAL_HOST: pihole.local
      TZ: 'Europe/London'
      WEBPASSWORD: pihole
    restart: unless-stopped
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.pihole.rule=Host(`pihole.local`, `pi.hole`)"
       - "traefik.http.routers.pihole.entrypoints=web"
       - "traefik.http.services.pihole.loadbalancer.server.port=80"
