version: "3.7"

services:

# HTPC Portal
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/heimdall:/config
    ports:
      - "80:80"
    environment:
      PGID: 1000
      PUID: 1000
    restart: unless-stopped

# TV
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/sonarr:/config
      - ${TV_DESTINATION_PATH}:/tv
      - ${PROCESSING_PATH}/downloads/complete:/downloads
    ports:
      - "8989:8989"
    environment:
      PGID: 1000
      PUID: 1000
    restart: unless-stopped

# Movies
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/radarr:/config
      - ${MOVIE_DESTINATION_PATH}:/movies
      - ${PROCESSING_PATH}/downloads/complete:/downloads
    ports:
      - "7878:7878"
    environment:
      PGID: 1000
      PUID: 1000
    restart: unless-stopped

# Torrent Proxy
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/jackett:/config
      - ${PROCESSING_PATH}/jackett-downloads:/downloads
    ports:
      - "9117:9117"
    environment:
      PGID: 1000
      PUID: 1000
    restart: unless-stopped

# Torrent Downloader
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/transmission:/config
      - ${PROCESSING_PATH}/downloads:/downloads
      - ${PROCESSING_PATH}/jackett-downloads:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      PGID: 1000
      PUID: 1000
    restart: unless-stopped

# Tor proxy so jackett can bypass ISP filters (NOT for anonymity - use something like Tails for that)
  torproxy:
    container_name: torproxy
    image: rdsubhas/tor-privoxy-alpine
    ports:
      - "8118:8118"
      - "9050:9050"
    restart: unless-stopped

# Auto update containers
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    command: --cleanup --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
